//
//  Localizable.h
//  box-Staff-Manager
//
//  Created by Yu Huang on 2018/6/27.
//  Copyright © 2018年 2se. All rights reserved.
//

#ifndef Localizable_h
#define Localizable_h

#define PerfectInformationVCTitle  NSLocalizedString(@"PerfectInformationVCTitle", nil)
#define PerfectInformationVCNameText  NSLocalizedString(@"PerfectInformationVCNameText", nil)
#define PerfectInformationVCPasswordText  NSLocalizedString(@"PerfectInformationVCPasswordText", nil)
#define PerfectInformationVCVerifyText  NSLocalizedString(@"PerfectInformationVCVerifyText", nil)
#define PerfectInformationVCAlertLab  NSLocalizedString(@"PerfectInformationVCAlertLab", nil)
#define PerfectInformationVCConfirmBtn  NSLocalizedString(@"PerfectInformationVCConfirmBtn", nil)
#define PerfectInformationVCAlertOne  NSLocalizedString(@"PerfectInformationVCAlertOne", nil)
#define PerfectInformationVCAlertTwo  NSLocalizedString(@"PerfectInformationVCAlertTwo", nil)
#define PerfectInformationVCAlertThree  NSLocalizedString(@"PerfectInformationVCAlertThree", nil)
#define PerfectInformationVCCheckPwd  NSLocalizedString(@"PerfectInformationVCCheckPwd", nil)
#define DepartmentVCAddDepartment  NSLocalizedString(@"DepartmentVCAddDepartment", nil)
#define DepartmentVCTitle  NSLocalizedString(@"DepartmentVCTitle", nil)
#define DepartmentVCTopTitle  NSLocalizedString(@"DepartmentVCTopTitle", nil)
#define AddDepartmentVCTitle  NSLocalizedString(@"AddDepartmentVCTitle", nil)
#define Cancel  NSLocalizedString(@"Cancel", nil)
#define AddDepartmentVCComplete  NSLocalizedString(@"AddDepartmentVCComplete", nil)
#define AddDepartmentVCPlaceholder  NSLocalizedString(@"AddDepartmentVCPlaceholder", nil)
#define AddDepartmentVCAlert  NSLocalizedString(@"AddDepartmentVCAlert", nil)
#define Affirm  NSLocalizedString(@"Affirm", nil)
#define delete  NSLocalizedString(@"delete", nil)
#define SureToDelete  NSLocalizedString(@"SureToDelete", nil)
#define DepartmentTableViewCellAddDepartment  NSLocalizedString(@"DepartmentTableViewCellAddDepartment", nil)
#define DepartmentDetailVCTitle  NSLocalizedString(@"DepartmentDetailVCTitle", nil)
#define DepartmentDetailVCDepartmentlab  NSLocalizedString(@"DepartmentDetailVCDepartmentlab", nil)
#define DepartmentDetailVCMember  NSLocalizedString(@"DepartmentDetailVCMember", nil)
#define Other  NSLocalizedString(@"Other", nil)
#define SelectDepartmemt  NSLocalizedString(@"SelectDepartmemt", nil)
#define LoginButton  NSLocalizedString(@"LoginButton", nil)
#define TransferVCETHAlert  NSLocalizedString(@"TransferVCETHAlert", nil)
#define AccountLockup  NSLocalizedString(@"AccountLockup", nil)
#define AccountPasswordError  NSLocalizedString(@"AccountPasswordError", nil)
#define AccountPasswordHour  NSLocalizedString(@"AccountPasswordHour", nil)
#define AccountPasswordTimes  NSLocalizedString(@"AccountPasswordTimes", nil)
#define AccountPasswordAlert  NSLocalizedString(@"AccountPasswordAlert", nil)
#define SetApprovalAmountVCTitle  NSLocalizedString(@"SetApprovalAmountVCTitle", nil)
#define LimitTimes  NSLocalizedString(@"LimitTimes", nil)
#define LimitTimesPlaceholder  NSLocalizedString(@"LimitTimesPlaceholder", nil)
#define ApplyForCurrency  NSLocalizedString(@"ApplyForCurrency", nil)
#define LimitCurrencyPlaceholder  NSLocalizedString(@"LimitCurrencyPlaceholder", nil)
#define LimitAlertAffirm  NSLocalizedString(@"LimitAlertAffirm", nil)
#define LimitAlertTitle  NSLocalizedString(@"LimitAlertTitle", nil)
#define LimitAlertContent  NSLocalizedString(@"LimitAlertContent", nil)
#define SearchCurrency  NSLocalizedString(@"SearchCurrency", nil)
#define SubmitApproval  NSLocalizedString(@"SubmitApproval", nil)
#define LimitAlert  NSLocalizedString(@"LimitAlert", nil)
#define PleaseInput  NSLocalizedString(@"PleaseInput", nil)
#define ApplyForLimit  NSLocalizedString(@"ApplyForLimit", nil)
#define Limit  NSLocalizedString(@"Limit", nil)
#define viewLog  NSLocalizedString(@"viewLog", nil)
#define cancelApproval  NSLocalizedString(@"cancelApproval", nil)
#define ApprovalBusinessSucceed  NSLocalizedString(@"ApprovalBusinessSucceed", nil)
#define ApprovalBusinessFail  NSLocalizedString(@"ApprovalBusinessFail", nil)
#define Reason  NSLocalizedString(@"Reason", nil)
#define SelectCurrency  NSLocalizedString(@"SelectCurrency", nil)
#define RemainingSum  NSLocalizedString(@"RemainingSum", nil)
#define TransferCancel  NSLocalizedString(@"TransferCancel", nil)
#define RefuseTransfer  NSLocalizedString(@"RefuseTransfer", nil)
#define RefuseTransferInfo  NSLocalizedString(@"RefuseTransferInfo", nil)
#define Submit  NSLocalizedString(@"Submit", nil)
#define RefuseApprovalPlacehode  NSLocalizedString(@"RefuseApprovalPlacehode", nil)
#define HomeMeVCTitle  NSLocalizedString(@"HomeMeVCTitle", nil)
#define UserName  NSLocalizedString(@"UserName", nil)
#define AccountAddress  NSLocalizedString(@"AccountAddress", nil)
#define BindCode  NSLocalizedString(@"BindCode", nil)
#define ServerAddress  NSLocalizedString(@"ServerAddress", nil)
#define Departments  NSLocalizedString(@"Departments", nil)
#define ModifyPassword  NSLocalizedString(@"ModifyPassword", nil)
#define AboutBOX  NSLocalizedString(@"AboutBOX", nil)
#define CurrentVersion  NSLocalizedString(@"CurrentVersion", nil)
#define CopyAddress  NSLocalizedString(@"CopyAddress", nil)
#define PreserveQRCode  NSLocalizedString(@"PreserveQRCode", nil)
#define CopyAddressSucceed  NSLocalizedString(@"CopyAddressSucceed", nil)
#define SaveFailure  NSLocalizedString(@"SaveFailure", nil)
#define SavePicturesucceed  NSLocalizedString(@"SavePicturesucceed", nil)
#define ScanAdressVCTitle  NSLocalizedString(@"ScanAdressVCTitle", nil)
#define ScanAdressVCScanLab  NSLocalizedString(@"ScanAdressVCScanLab", nil)
#define ScanAdressVCDetailLab  NSLocalizedString(@"ScanAdressVCDetailLab", nil)
#define ScanAdressVCAuthorizeBtn  NSLocalizedString(@"ScanAdressVCAuthorizeBtn", nil)
#define ScanAdressVCAleartLab  NSLocalizedString(@"ScanAdressVCAleartLab", nil)
#define ScanAdressVCIknown  NSLocalizedString(@"ScanAdressVCIknown", nil)
#define ScanAdressVCAlertMessage  NSLocalizedString(@"ScanAdressVCAlertMessage", nil)
#define ModificatePasswordVCoriginalPawd  NSLocalizedString(@"ModificatePasswordVCoriginalPawd", nil)
#define ModificatePasswordVCoriginalPawdInfo  NSLocalizedString(@"ModificatePasswordVCoriginalPawdInfo", nil)
#define ModificatePasswordVCpawdnew  NSLocalizedString(@"ModificatePasswordVCpawdnew", nil)
#define ModificatePasswordVCpawdnewInfo  NSLocalizedString(@"ModificatePasswordVCpawdnewInfo", nil)
#define ModificatePasswordVCRenewPawdInfo  NSLocalizedString(@"ModificatePasswordVCRenewPawdInfo", nil)
#define ModificatePasswordVCVerify  NSLocalizedString(@"ModificatePasswordVCVerify", nil)
#define ModificatePasswordVCAleartSucceed  NSLocalizedString(@"ModificatePasswordVCAleartSucceed", nil)
#define ModificatePasswordVCOriginalError  NSLocalizedString(@"ModificatePasswordVCOriginalError", nil)
#define ModifyServerAddressVCTitle  NSLocalizedString(@"ModifyServerAddressVCTitle", nil)
#define ModifyServerAddressVCAddress  NSLocalizedString(@"ModifyServerAddressVCAddress", nil)
#define ModifyServerAddressVCInfo  NSLocalizedString(@"ModifyServerAddressVCInfo", nil)
#define ModifyServerAddressVCVerifyBtn  NSLocalizedString(@"ModifyServerAddressVCVerifyBtn", nil)
#define Create  NSLocalizedString(@"Create", nil)
#define HomeServiceVCTitle  NSLocalizedString(@"HomeServiceVCTitle", nil)
#define HomeServiceVCApprovalWorkflow  NSLocalizedString(@"HomeServiceVCApprovalWorkflow", nil)
#define HomeServiceVCAsset  NSLocalizedString(@"HomeServiceVCAsset", nil)
#define HomeServiceVCOrganization  NSLocalizedString(@"HomeServiceVCOrganization", nil)
#define HomeServiceVCDepartment  NSLocalizedString(@"HomeServiceVCDepartment", nil)
#define ApprovalBusinessApprovaling  NSLocalizedString(@"ApprovalBusinessApprovaling", nil)
#define ApprovalBusinessSucceed  NSLocalizedString(@"ApprovalBusinessSucceed", nil)
#define ApprovalBusinessFail  NSLocalizedString(@"ApprovalBusinessFail", nil)
#define ApprovalBusinessAwait  NSLocalizedString(@"ApprovalBusinessAwait", nil)
#define ApprovalBusinessDetailTitle  NSLocalizedString(@"ApprovalBusinessDetailTitle", nil)
#define SearchSubordinates  NSLocalizedString(@"SearchSubordinates", nil)
#define Replace  NSLocalizedString(@"Replace", nil)
#define AssetAmountVCTitle  NSLocalizedString(@"AssetAmountVCTitle", nil)
#define Detailed  NSLocalizedString(@"Detailed", nil)
#define CreateApprovalFlowVCTitle  NSLocalizedString(@"CreateApprovalFlowVCTitle", nil)
#define CreateApprovalFlowVCflowNameLab  NSLocalizedString(@"CreateApprovalFlowVCflowNameLab", nil)
#define CreateApprovalFlowVCflowNameInfo  NSLocalizedString(@"CreateApprovalFlowVCflowNameInfo", nil)
#define CreateApprovalFlowVCflowLimitLab  NSLocalizedString(@"CreateApprovalFlowVCflowLimitLab", nil)
#define CreateApprovalFlowVCflowLimitInfo  NSLocalizedString(@"CreateApprovalFlowVCflowLimitInfo", nil)
#define CreateApprovalFlowVCApprovalLevels  NSLocalizedString(@"CreateApprovalFlowVCApprovalLevels", nil)
#define CreateApprovalFlowVCAddLevels  NSLocalizedString(@"CreateApprovalFlowVCAddLevels", nil)
#define CreateApprovalFlowVCAddLevelsAleart  NSLocalizedString(@"CreateApprovalFlowVCAddLevelsAleart", nil)
#define CreateApprovalFlowVCBlankAleart  NSLocalizedString(@"CreateApprovalFlowVCBlankAleart", nil)
#define CreateApprovalFlowVCBlankAleartZero  NSLocalizedString(@"CreateApprovalFlowVCBlankAleartZero", nil)
#define CreateApprovalFlowVCSuccessAleart  NSLocalizedString(@"CreateApprovalFlowVCSuccessAleart", nil)
#define NextStep  NSLocalizedString(@"NextStep", nil)
#define Search  NSLocalizedString(@"Search", nil)
#define AddApprovalMenberVC  NSLocalizedString(@"AddApprovalMenberVC", nil)
#define AddApprovalMenberVCSectionOne  NSLocalizedString(@"AddApprovalMenberVCSectionOne", nil)
#define AddApprovalMenberVCSectionTwo  NSLocalizedString(@"AddApprovalMenberVCSectionTwo", nil)
#define ApprovalSucceedBusiness  NSLocalizedString(@"ApprovalSucceedBusiness", nil)
#define ApprovalFailBusiness  NSLocalizedString(@"ApprovalFailBusiness", nil)
#define SearchMember  NSLocalizedString(@"SearchMember", nil)
#define AssetAmountfreeze  NSLocalizedString(@"AssetAmountfreeze", nil)
#define ApprovalMenber  NSLocalizedString(@"ApprovalMenber", nil)
#define ApprovalMenberAmount  NSLocalizedString(@"ApprovalMenberAmount", nil)
#define Add  NSLocalizedString(@"Add", nil)
#define Edit  NSLocalizedString(@"Edit", nil)
#define NoAddressAdded  NSLocalizedString(@"NoAddressAdded", nil)
#define HomeDirectoryVCTitle  NSLocalizedString(@"HomeDirectoryVCTitle", nil)
#define HomeDirectoryVCAddAddress  NSLocalizedString(@"HomeDirectoryVCAddAddress", nil)
#define AddDirectoryVCTitle  NSLocalizedString(@"AddDirectoryVCTitle", nil)
#define AddDirectoryVCRightTitle  NSLocalizedString(@"AddDirectoryVCRightTitle", nil)
#define AddDirectoryCurrency  NSLocalizedString(@"AddDirectoryCurrency", nil)
#define AddDirectoryName  NSLocalizedString(@"AddDirectoryName", nil)
#define AddDirectoryNameInfo  NSLocalizedString(@"AddDirectoryNameInfo", nil)
#define AddDirectoryVCAddress  NSLocalizedString(@"AddDirectoryVCAddress", nil)
#define AddDirectoryVCAddressInfo  NSLocalizedString(@"AddDirectoryVCAddressInfo", nil)
#define AddDirectoryVCRemark  NSLocalizedString(@"AddDirectoryVCRemark", nil)
#define AddDirectoryVCRemarkInfo  NSLocalizedString(@"AddDirectoryVCRemarkInfo", nil)
#define AddDirectoryVCcurrencyInfo  NSLocalizedString(@"AddDirectoryVCcurrencyInfo", nil)
#define AddDirectoryVCError  NSLocalizedString(@"AddDirectoryVCError", nil)
#define SearchCurrency  NSLocalizedString(@"SearchCurrency", nil)
#define EditorDirectoryVCTitle  NSLocalizedString(@"EditorDirectoryVCTitle", nil)
#define EditorDirectoryVCError  NSLocalizedString(@"EditorDirectoryVCError", nil)
#define SystemInfo  NSLocalizedString(@"SystemInfo", nil)
#define HomeBoxVCScanTitle  NSLocalizedString(@"HomeBoxVCScanTitle", nil)
#define HomeBoxVCTransferTitle  NSLocalizedString(@"HomeBoxVCTransferTitle", nil)
#define HomeBoxVCPaymentCodeTitle  NSLocalizedString(@"HomeBoxVCPaymentCodeTitle", nil)
#define HomeBoxVCTaskTitle  NSLocalizedString(@"HomeBoxVCTaskTitle", nil)
#define HomeBoxVCTransferAwait  NSLocalizedString(@"HomeBoxVCTransferAwait", nil)
#define HomeBoxVCcheckDetailBtn  NSLocalizedString(@"HomeBoxVCcheckDetailBtn", nil)
#define HomeBoxVCsystemInfo  NSLocalizedString(@"HomeBoxVCsystemInfo", nil)
#define HomeBoxVCsystemUpdate  NSLocalizedString(@"HomeBoxVCsystemUpdate", nil)
#define HomeBoxVCTransferRecord  NSLocalizedString(@"HomeBoxVCTransferRecord", nil)
#define HomeBoxVCTransferExamine  NSLocalizedString(@"HomeBoxVCTransferExamine", nil)
#define HomeBoxVCInitiate  NSLocalizedString(@"HomeBoxVCInitiate", nil)
#define HomeBoxVCParticipateIn  NSLocalizedString(@"HomeBoxVCParticipateIn", nil)
#define HomeBoxVCTransferSubLab  NSLocalizedString(@"HomeBoxVCTransferSubLab", nil)
#define MinersFeeLabAlert  NSLocalizedString(@"MinersFeeLabAlert", nil)
#define AmountTfAlert  NSLocalizedString(@"AmountTfAlert", nil)
#define TransferVCTitle  NSLocalizedString(@"TransferVCTitle", nil)
#define TransferVCApprovalProcess  NSLocalizedString(@"TransferVCApprovalProcess", nil)
#define TransferVCApprovalProcessInfo  NSLocalizedString(@"TransferVCApprovalProcessInfo", nil)
#define TransferVCRightTitle  NSLocalizedString(@"TransferVCRightTitle", nil)
#define TransferVCCurrency  NSLocalizedString(@"TransferVCCurrency", nil)
#define TransferVCReceiptAddress  NSLocalizedString(@"TransferVCReceiptAddress", nil)
#define TransferVCReceiptAddressInfo  NSLocalizedString(@"TransferVCReceiptAddressInfo", nil)
#define TransferVCAmount  NSLocalizedString(@"TransferVCAmount", nil)
#define TransferVCAmountInfo  NSLocalizedString(@"TransferVCAmountInfo", nil)
#define TransferVCApplyReason  NSLocalizedString(@"TransferVCApplyReason", nil)
#define TransferVCApplyReasonInfo  NSLocalizedString(@"TransferVCApplyReasonInfo", nil)
#define TransferVCMinersFee  NSLocalizedString(@"TransferVCMinersFee", nil)
#define TransferVCMinersFeeSlow  NSLocalizedString(@"TransferVCMinersFeeSlow", nil)
#define TransferVCMinersFeeFast  NSLocalizedString(@"TransferVCMinersFeeFast", nil)
#define TransferVCBtnTitle  NSLocalizedString(@"TransferVCBtnTitle", nil)
#define tansferCodeVCTitle  NSLocalizedString(@"tansferCodeVCTitle", nil)
#define tansferCodeVCScanLab  NSLocalizedString(@"tansferCodeVCScanLab", nil)
#define tansferCodeVCSaveAddressBtnb  NSLocalizedString(@"tansferCodeVCSaveAddressBtnb", nil)
#define tansferCodeVCSaveAddressSucced  NSLocalizedString(@"tansferCodeVCSaveAddressSucced", nil)
#define TransferAwaitVCTitle  NSLocalizedString(@"TransferAwaitVCTitle", nil)
#define TransferAwaitVCAgreeApprovalBtn  NSLocalizedString(@"TransferAwaitVCAgreeApprovalBtn", nil)
#define TransferAwaitVCRefuseApprovalBtn  NSLocalizedString(@"TransferAwaitVCRefuseApprovalBtn", nil)
#define TransferTopViewApprovaling  NSLocalizedString(@"TransferTopViewApprovaling", nil)
#define TransferTopViewApprovalSucceed  NSLocalizedString(@"TransferTopViewApprovalSucceed", nil)
#define TransferTopViewApprovalFail  NSLocalizedString(@"TransferTopViewApprovalFail", nil)
#define TransferTopViewApprovalAgreen  NSLocalizedString(@"TransferTopViewApprovalAgreen", nil)
#define TransferTopViewApprovalCancel  NSLocalizedString(@"TransferTopViewApprovalCancel", nil)
#define SearchApprovalFlow  NSLocalizedString(@"SearchApprovalFlow", nil)
#define PrivatePasswordbackupLab  NSLocalizedString(@"PrivatePasswordbackupLab", nil)
#define PrivatePasswordComfirm  NSLocalizedString(@"PrivatePasswordComfirm", nil)
#define TransferViewTitle  NSLocalizedString(@"TransferViewTitle", nil)
#define TransferViewApproval  NSLocalizedString(@"TransferViewApproval", nil)
#define TransferViewCurrency  NSLocalizedString(@"TransferViewCurrency", nil)
#define TransferViewReceiptAddress  NSLocalizedString(@"TransferViewReceiptAddress", nil)
#define TransferViewAmount  NSLocalizedString(@"TransferViewAmount", nil)
#define TransferViewApplyReason  NSLocalizedString(@"TransferViewApplyReason", nil)
#define TransferViewMinersFee  NSLocalizedString(@"TransferViewMinersFee", nil)
#define TransferViewBtnTitle  NSLocalizedString(@"TransferViewBtnTitle", nil)
#define TransferViewBtnCommit  NSLocalizedString(@"TransferViewBtnCommit", nil)
#define TransferViewInputTitle  NSLocalizedString(@"TransferViewInputTitle", nil)
#define TransferViewAchieveTitle  NSLocalizedString(@"TransferViewAchieveTitle", nil)
#define TransferViewAchieveSubTitle  NSLocalizedString(@"TransferViewAchieveSubTitle", nil)
#define TransferViewAchieveDid  NSLocalizedString(@"TransferViewAchieveDid", nil)
#define TransferViewPutPassWord  NSLocalizedString(@"TransferViewPutPassWord", nil)
#define TransferViewPassWordError  NSLocalizedString(@"TransferViewPassWordError", nil)
#define TransferRecordTableViewCellTransferingAwait  NSLocalizedString(@"TransferRecordTableViewCellTransferingAwait", nil)
#define TransferRecordTableViewCellTransfering  NSLocalizedString(@"TransferRecordTableViewCellTransfering", nil)
#define TransferRecordTableViewCellTransferStateSucceed  NSLocalizedString(@"TransferRecordTableViewCellTransferStateSucceed", nil)
#define TransferRecordTableViewCellTransferStateSucceedTransfing  NSLocalizedString(@"TransferRecordTableViewCellTransferStateSucceedTransfing", nil)
#define TransferRecordTableViewCellTransferStateFail  NSLocalizedString(@"TransferRecordTableViewCellTransferStateFail", nil)
#define TransferRecordTableViewCellRecharge  NSLocalizedString(@"TransferRecordTableViewCellRecharge", nil)
#define TransferRecordTableViewCellTransferFail  NSLocalizedString(@"TransferRecordTableViewCellTransferFail", nil)
#define TransferRecordTableViewCellTransferCancel  NSLocalizedString(@"TransferRecordTableViewCellTransferCancel", nil)
#define TransferTopViewCurrency  NSLocalizedString(@"TransferTopViewCurrency", nil)
#define TransferTopViewReceiptAddress  NSLocalizedString(@"TransferTopViewReceiptAddress", nil)
#define TransferTopViewAmount  NSLocalizedString(@"TransferTopViewAmount", nil)
#define TransferTopViewApplyMenber  NSLocalizedString(@"TransferTopViewApplyMenber", nil)
#define TransferTopViewApplyReason  NSLocalizedString(@"TransferTopViewApplyReason", nil)
#define TransferTopViewMinersFee  NSLocalizedString(@"TransferTopViewMinersFee", nil)
#define TransferTopViewStateOne  NSLocalizedString(@"TransferTopViewStateOne", nil)
#define TransferTopViewStateTwo  NSLocalizedString(@"TransferTopViewStateTwo", nil)
#define TransferTopViewStateThreeTransfing  NSLocalizedString(@"TransferTopViewStateThreeTransfing", nil)
#define TransferTopViewStateThree  NSLocalizedString(@"TransferTopViewStateThree", nil)
#define TransferTopViewStateFour  NSLocalizedString(@"TransferTopViewStateFour", nil)
#define TransferTopViewStateCancel  NSLocalizedString(@"TransferTopViewStateCancel", nil)
#define TransferTopViewTitle  NSLocalizedString(@"TransferTopViewTitle", nil)
#define labelTipInfo  NSLocalizedString(@"labelTipInfo", nil)
#define InitAccountVCTitle  NSLocalizedString(@"InitAccountVCTitle", nil)
#define PerfectInformationVCLaber  NSLocalizedString(@"PerfectInformationVCLaber", nil)
#define PerfectInformationVCSubLaber  NSLocalizedString(@"PerfectInformationVCSubLaber", nil)
#define EmpowermentSuccess  NSLocalizedString(@"EmpowermentSuccess", nil)
#define EmpowermentFailed  NSLocalizedString(@"EmpowermentFailed", nil)
#define RequestError  NSLocalizedString(@"RequestError", nil)
#define Handing  NSLocalizedString(@"Handing", nil)
#define ScanCodeWSprogress  NSLocalizedString(@"ScanCodeWSprogress", nil)
#define ScanCodeVCTitle  NSLocalizedString(@"ScanCodeVCTitle", nil)
#define PerfectInformationVCTorchlight  NSLocalizedString(@"PerfectInformationVCTorchlight", nil)
#define PerfectInformationVCTorchheight  NSLocalizedString(@"PerfectInformationVCTorchheight", nil)
#define PerfectInformationVCScanResult  NSLocalizedString(@"PerfectInformationVCScanResult", nil)
#define PerfectInformationVCErrorCode  NSLocalizedString(@"PerfectInformationVCErrorCode", nil)
#define ApprovalBusinessCancel  NSLocalizedString(@"ApprovalBusinessCancel", nil)
#define ApprovalCancelAlertTitleOne  NSLocalizedString(@"ApprovalCancelAlertTitleOne", nil)
#define ApprovalCancelAlertMessageOne  NSLocalizedString(@"ApprovalCancelAlertMessageOne", nil)
#define ApprovalCancelAlertTitleTwo  NSLocalizedString(@"ApprovalCancelAlertTitleTwo", nil)
#define ApprovalCancelAlertMessageTwo  NSLocalizedString(@"ApprovalCancelAlertMessageTwo", nil)
#define RefuseTransfer  NSLocalizedString(@"RefuseTransfer", nil)
#define RefuseTransferInfo  NSLocalizedString(@"RefuseTransferInfo", nil)
#define RefuseTransferPlacehode  NSLocalizedString(@"RefuseTransferPlacehode", nil)
#define InitiateApplication  NSLocalizedString(@"InitiateApplication", nil)
#define SystemApprovalSucceed  NSLocalizedString(@"SystemApprovalSucceed", nil)
#define SystemApprovalFail  NSLocalizedString(@"SystemApprovalFail", nil)





























#endif /* Localizable_h */
